don't release aarch64-pc-windows-msvc
fails with

running rustup to ensure you have aarch64-pc-windows-msvc installed
info: component 'rust-std' for target 'aarch64-pc-windows-msvc' is up to date
building aarch64-pc-windows-msvc target, from x86_64-unknown-linux-gnu host, via cargo-xwin, using cargo profile dist --workspace)
⏬ Downloading MSVC CRT...
✅ Downloaded MSVC CRT in 1m 13s.
error: rustc 1.87.0 is not supported by the following packages:
  sed@0.1.1 requires rustc 1.88
  sed@0.1.1 requires rustc 1.88
  sed@0.1.1 requires rustc 1.88
  sed@0.1.1 requires rustc 1.88
  sysinfo@0.37.2 requires rustc 1.88

  × failed to find bin sed.exe for path+file:///__w/sed/sed#0.1.1
  help: did the above build fail?